id: IF61189C6
legacy_id: P008033
ocr_import_info:
  bdrc_scan_id: W3CN4275
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T01:57:25'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T14:23:38.206102+00:00'
last_modified: 2022-09-03 22:23:50.931946
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN4275
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN4275
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བློ་སྦྱོང་དང་ཞལ་གདམས་ཉེར་མཁོ་ཕྱོགས་བསྒྲིགས།
statistics:
  ocr_word_mean_confidence_index: 0.6580699040488598
  ocr_word_median_confidence_index: 0.8899999856948853
quality: null
bases:
  I3CN4296:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN4296
      total_pages: 368
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN4296.txt
    statistics:
      ocr_word_median_confidence_index: 0.8899999856948853
      ocr_word_mean_confidence_index: 0.6580699040488598
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
