id: P008033
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 12:56:48.727057
source_metadata:
  id: bdr:W3CN4275
  title: བློ་སྦྱོང་དང་ཞལ་གདམས་ཉེར་མཁོ་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    7d6220f4753a45468792dc95b95b6eff:
      image_group_id: I3CN4296
      title: Volume 1 of blo sbyong dang zhal gdams nyer mkho phyogs bsgrigs/
      volume_number: 1
      total_pages: 368
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
