id: P008033
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN4275
  title: བློ་སྦྱོང་དང་ཞལ་གདམས་ཉེར་མཁོ་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    dbe14b66b30a4f47b9e6bb70a38e6232:
      image_group_id: I3CN4296
      title: ''
      volume_number: 1
      total_pages: 368
ebook_metadata:
  title: བློ་སྦྱོང་དང་ཞལ་གདམས་ཉེར་མཁོ་ཕྱོགས་བསྒྲིགས།
  author: ''
  sku: P008033
  cover: cover.jpg
  layers:
  - pagination
